version: "3.7"
services:
  front_app:
    build: /card-transfer/.
    restart: on-failure
    ports:
      - "3000:3000"

  transfer_app:
    build: .
    links:
      - "front_app"
    restart: on-failure
    ports:
      - "5500:5500"
    volumes:
      - "./mydb:/mydb"


